### ISSUE TITLE
How are flops (floating point operations) calculated in this article? 

### ISSUE THREAD

**Issue by hanyuchen8145** [Yasir-Ghunaim/RealtimeOCL#3]
Hello, how are flops (floating point operations) calculated in this article? Where can I see it? Is it different from the way other codes calculate?I am very interested in your article, so I may ask a little too many questions, please understand.

**Comment by Yasir-Ghunaim** [comment]
Are you referring to this [article](https://github.com/Yasir-Ghunaim/RealtimeOCL/blob/main/measuring_delay.md)? If so, this is a tutorial on how to calculate the rcomplexity of a given method using the flops measured by the code. It is not different from the code. Can you please clarify the question?
